DATALOADER:
  NUM_WORKERS: 4

  IMAGE_BATCH_SIZE: 1

  SAMPLER_TRAIN:
  SAMPLER_TEST:

DATASETS:
  TRAIN:
    NAMES: []
    PARAMS: []

  TEST:
    NAMES: []
    PARAMS: []

MODEL:
  DEVICE: cuda
  NAME:
  WEIGHTS:

SOLVER:
  AMP:
    ENABLED: false

  LOG_PERIOD: 20
  CHECKPOINT_PERIOD: 5000

  CLIP_GRADIENTS:
    ENABLED: false

  BASE_LR: 0.001
  BASE_LR_END: 0.5
  MOMENTUM: 0.9
  NESTEROV: false
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: null

  LR_SCHEDULER_NAME:
  STEPS: []
  MAX_ITER: 0
  GAMMA: 0.1

  RESCALE_INTERVAL: false
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear

TEST:
  EVAL_PERIOD: 5000

CUDNN_BENCHMARK: False
SEED: -1
VERSION: 1
OUTPUT_DIR: null
