_BASE_: ../../../coach/config/base.yaml

DATALOADER:
  NUM_WORKERS: 4

  IMAGE_BATCH_SIZE: 1

  SAMPLER_TRAIN: TrainingSampler

DATASETS:
  TRAIN: 
    NAMES: [BlenderDataset]
    PARAMS: [
      [/home/vrlab/share/nerf-dataset/nerf_synthetic/hotdog]
    ]

  TEST:
    NAMES: []
    PARAMS: [
      []
    ]

MODEL:
  NAME: NeRF
  WEIGHTS:

  SAMPLER:
    NAME: build_bbox_sampler
    PROJECTION: perspective
    RAY_BATCH_SIZE: 4096

  SCENE:
    NAME: build_vanilla_scene

    POSITIONAL_ENCODER:
      NAME: build_trigonometric_encoder
      N_FREQUENCIES: 10

    DIRECTIONAL_ENCODER:
      NAME: build_trigonometric_encoder
      N_FREQUENCIES: 4

  RENDERER:
    NAME: build_volume_renderer

  CRITERION:
    NAME: build_pytorch_criterion
    TYPE: MSELoss

SOLVER:
  AMP:
    ENABLED: False

  LOG_PERIOD: 20
  CHECKPOINT_PERIOD: 5000

  BASE_LR: 0.001
  LR_SCHEDULER_NAME: MultiStepParamScheduler
  STEPS: [100000, 150000]
  MAX_ITER: 200000
  GAMMA: 0.1

  RESCALE_INTERVAL: False
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: project/nerf/output
