DATALOADER:
  NUM_WORKERS: 4

  IMAGE_BATCH_SIZE: 1
  RAY_BATCH_SIZE: 4096

  SAMPLER_TRAIN: "TrainingSampler"
DATASETS:
  TRAIN: []
MODEL:
  DEVICE: "cuda"
  NAME: "NeRF"
  WEIGHTS:

  SAMPLER:
    NAME: "build_random_sampler"
    PROJECTION: "perspective"

  SCENE:
    NAME: "build_vanilla_scene"
    POSITIONAL_ENCODER: "build_trigonometric_encoder"
    DIRECTIONAL_ENCODER: "build_trigonometric_encoder"

  RENDERER:
    NAME: "build_volume_renderer"

  CRITERION:
    NAME: "build_pytorch_criterion"
    TYPE: "MSELoss"

OUTPUT_DIR: "output"
SOLVER:
  AMP:
    ENABLED: False
  LOG_PERIOD: 20
  CHECKPOINT_PERIOD: 5000

  BASE_LR: 1e-3
  LR_SCHEDULER_NAME: MultiStepParamScheduler
  STEPS: (100000, 150000)
  MAX_ITER: 200000
  GAMMA: 0.1

  RESCALE_INTERVAL: False
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
TEST:
  EVAL_PERIOD: 5000
VERSION: 1
