_BASE_: ../../../coach/config/base.yaml

DATALOADER:
  NUM_WORKERS: 4

  IMAGE_BATCH_SIZE: 512

  SAMPLER_TRAIN: TrainingSampler
  SAMPLER_TEST: InferenceSampler

DATASETS:
  TRAIN: 
    NAMES: [MNISTDataset]
    PARAMS: [
      [/home/vrlab/share]
    ]

  TEST:
    NAMES: [MNISTDataset]
    PARAMS: [
      [/home/vrlab/share]
    ]

MODEL:
  DEVICE: cuda
  NAME: AutoEncoder
  WEIGHTS:

  IMAGE_SIZE: 28
  IN_CHANNELS: 784
  LATENT_CHANNELS: 8

  ENCODER:
    NAME: build_ae_mlp_encoder
    HIDDEN_LAYERS: 4
    HIDDEN_CHANNELS: [512, 128, 16]
    BIAS: True

  DECODER:
    NAME: build_ae_mlp_decoder
    HIDDEN_LAYERS: 4
    HIDDEN_CHANNELS: [16, 128, 512]
    BIAS: True

  CRITERION:
    NAME: build_pytorch_criterion
    TYPE: BCEWithLogitsLoss

SOLVER:
  AMP:
    ENABLED: True

  LOG_PERIOD: 1000
  CHECKPOINT_PERIOD: 20000

  BASE_LR: 1
  LR_SCHEDULER_NAME: MultiStepParamScheduler
  STEPS: [37500, 56250, 84375]
  MAX_ITER: 93750
  GAMMA: 0.4

  RESCALE_INTERVAL: False
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear

  SCHEDULER: MultiStepParamScheduler

TEST:
  EVAL_PERIOD: 5000

VERSION: 1

OUTPUT_DIR: project/vae/output/ae_mlp
