_BASE_: ../../../coach/config/base.yaml

DATALOADER:
  NUM_WORKERS: 4

  IMAGE_BATCH_SIZE: 128

  SAMPLER_TRAIN: TrainingSampler

DATASETS:
  TRAIN: 
    NAMES: [MNISTDataset]
    PARAMS: [
      [/home/vrlab/share]
    ]

  TEST:
    NAMES: [MNISTDataset]
    PARAMS: [
      [/home/vrlab/share]
    ]

MODEL:
  DEVICE: cuda
  NAME: VariationalAutoEncoder
  WEIGHTS:

  IN_CHANNELS: 784
  LATENT_CHANNELS: 10

  ENCODER:
    NAME: build_vae_mlp_encoder
    HIDDEN_LAYERS: 3
    HIDDEN_CHANNELS: 512
    BIAS: True

  DECODER:
    NAME: build_vae_mlp_decoder
    HIDDEN_LAYERS: 3
    HIDDEN_CHANNELS: 512
    BIAS: True

  CRITERION:
    NAME: build_vae_criterion
    WEIGHT: 1.0

SOLVER:
  AMP:
    ENABLED: True

  LOG_PERIOD: 100
  CHECKPOINT_PERIOD: 10000

  BASE_LR: 0.001
  LR_SCHEDULER_NAME: MultiStepParamScheduler
  STEPS: [15000, 22500]
  MAX_ITER: 25000
  GAMMA: 0.1

  RESCALE_INTERVAL: False
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear

  SCHEDULER: MultiStepParamScheduler

TEST:
  EVAL_PERIOD: 5000

VERSION: 1

OUTPUT_DIR: project/vae/output
