_BASE_: ../../../coach/config/base.yaml

DATALOADER:
  NUM_WORKERS: 4

  IMAGE_BATCH_SIZE: 512

  SAMPLER_TRAIN: TrainingSampler
  SAMPLER_TEST: InferenceSampler

DATASETS:
  TRAIN: 
    NAMES: [MNISTDataset]
    PARAMS: [
      [/home/vrlab/share]
    ]

  TEST:
    NAMES: [MNISTDataset]
    PARAMS: [
      [/home/vrlab/share]
    ]

MODEL:
  DEVICE: cuda
  NAME: VariationalAutoEncoder
  WEIGHTS:

  IMAGE_SIZE: 28
  IN_CHANNELS: 784
  LATENT_CHANNELS: 8

  ENCODER:
    NAME: build_vae_mlp_encoder
    HIDDEN_LAYERS: 4
    HIDDEN_CHANNELS: [512, 128, 16]
    BIAS: True

  DECODER:
    NAME: build_vae_mlp_decoder
    HIDDEN_LAYERS: 4
    HIDDEN_CHANNELS: [16, 128, 512]
    BIAS: True

  CRITERION:
    NAME: build_vae_criterion
    WEIGHT: 10.0

SOLVER:
  AMP:
    ENABLED: False

  LOG_PERIOD: 1000
  CHECKPOINT_PERIOD: 20000

  BASE_LR: 0.001
  LR_SCHEDULER_NAME: MultiStepParamScheduler
  STEPS: [28130, 42185]
  MAX_ITER: 46875
  GAMMA: 0.1

  RESCALE_INTERVAL: False
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear

  SCHEDULER: MultiStepParamScheduler

TEST:
  EVAL_PERIOD: 5000

VERSION: 1

OUTPUT_DIR: project/vae/output/vae_mlp
