_BASE_: vae_mlp.yaml

MODEL:
  IMAGE_SIZE: 28
  IN_CHANNELS: 1
  LATENT_CHANNELS: 8

  ENCODER:
    NAME: build_vae_conv_encoder
    HIDDEN_LAYERS: 4
    HIDDEN_CHANNELS: [16, 32, 64]
    BIAS: True

  DECODER:
    NAME: build_vae_conv_decoder
    HIDDEN_LAYERS: 4
    HIDDEN_CHANNELS: [64, 32, 16]
    BIAS: True

  CRITERION:
    NAME: build_vae_criterion
    WEIGHT: 10.0

SOLVER:
  AMP:
    ENABLED: False

  LOG_PERIOD: 1000
  CHECKPOINT_PERIOD: 20000

  BASE_LR: 0.001
  LR_SCHEDULER_NAME: MultiStepParamScheduler
  STEPS: [28130, 42185]
  MAX_ITER: 46875
  GAMMA: 0.1

  RESCALE_INTERVAL: False
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear

  SCHEDULER: MultiStepParamScheduler

OUTPUT_DIR: project/vae/output/vae_conv
